import { Poppins } from "next/font/google"; // Import the Poppins font
import "./globals.css";
import Script from "next/script";

// Configure the Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"], // You can specify the font weights you want to include
});

export const metadata = {
  title: "Home | hobbycue",
  description: "Generated by create next app with bootstrap",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
          <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossOrigin="anonymous"
          strategy="beforeInteractive" // Ensures the script loads before the page is interactive
        />
      </head>
      <body className={poppins.className + " bg-white"}>
        {children}
       
      </body>
    </html>
  );
}
